# DTIO Configuration File
# This file defines which paths should be intercepted by DTIO
# 
# The configuration uses a simple include/exclude pattern matching system:
# - Paths are converted to absolute paths and sorted by length (longest first)
# - Include paths specify directories that should be monitored by DTIO
# - Exclude paths take precedence over include paths for fine-grained control
#
# Generated automatically by jarvis_dtio.dtio_run.pkg.DtioRun

# Paths to include for DTIO interception
# These directories and their subdirectories will be monitored
include:
  - "/tmp"
  - "/scratch"
  - "/mnt/shared"
  - "/data"

# Paths to exclude from DTIO interception (takes precedence over includes)
# Use these to exclude specific subdirectories or system paths
exclude:
  - "/tmp/system"
  - "/tmp/.X11-unix"
  - "/scratch/logs" 