WORKER_PATH: "${HOME}/test"
PFS_PATH: "${HOME}/pfs"
NATS_URL_CLIENT: "nats://localhost:4222/"
NATS_URL_SERVER: "nats://localhost:4223/"
MEMCACHED_URL_CLIENT: "--SERVER=localhost:11211"
MEMCACHED_URL_SERVER: "--SERVER=localhost:11212"
ASSIGNMENT_POLICY: "RANDOM"
TS_NUM_WORKER_THREADS: "8"
